name: Build PJSIP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-pjsip-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: sudo apt-get install -y libopencore-amrnb-dev libopus-dev libasound2-dev
    - name: configure
      working-directory: ./pjproject
      run: ./configure --prefix=$PWD/../linux_x86-64
    - name: make
      working-directory: ./pjproject
      run: make
    - name: delete previous lib
      continue-on-error: true
      run: |
        rm -r linux_x86-64/lib
        rm -r linux_x86-64/include
    - name: make install
      working-directory: ./pjproject
      run: make install
    - name: Commit Libs
      continue-on-error: true
      run: |
        git config --global user.name 'AWAH-SIP_CI'
        git config --global user.email 'AWAH-SIP@users.noreply.github.com'
        git pull
        git add linux_x86-64/\*
        git commit -m "Github Actions updated PJSIP-Libraries for linux_x86-64"
        git push

  build-pjsip-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: brew install opencore-amr
    - name: configure
      working-directory: ./pjproject
      run: CFLAGS="-I/usr/local/include -I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" ./configure --prefix=$PWD/../mac_x86-64
    - name: make
      working-directory: ./pjproject
      run: make
    - name: delete previous lib
      continue-on-error: true
      run: |
        rm -r mac_x86-64/lib
        rm -r mac_x86-64/include
    - name: make install
      working-directory: ./pjproject
      run: make install
    - name: Commit Libs
      continue-on-error: true
      run: |
        git config --global user.name 'AWAH-SIP_CI'
        git config --global user.email 'AWAH-SIP@users.noreply.github.com'
        git pull
        git add mac_x86-64/\*
        git commit -m "Github Actions updated PJSIP-Libraries for mac_x86-64"
        git push

  build-pjsip-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: get openssl
      working-directory: ./pjproject
      run: Invoke-WebRequest -Uri "https://mirror.firedaemon.com/OpenSSL/openssl-1.1.1n.zip" -OutFile ".\openssl.zip"
      shell: powershell
    - name: delete previous openSSL
      continue-on-error: true
      run: |
        rm -r win_x86-64\openssl-1.1
      shell: powershell
    - name: expand openssl
      working-directory: ./pjproject
      run: |
        Expand-Archive -LiteralPath .\openssl.zip -DestinationPath ..\win_x86-64\  -force; pwd
        cd ..\win_x86-64\openssl-1.1\x86
        Add-Content ..\..\..\pjproject\openssl_dir.txt $pwd.Path
      shell: powershell
    - name: check openssl folder
      working-directory: ./pjproject
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        dir "%OPENSSL_DIR%\include"
        dir "%OPENSSL_DIR%\lib"
      shell: cmd
    - name: Update config site
      run:
        cd pjproject/pjlib/include/pj; Add-Content config_site.h "`r`n#define PJ_HAS_SSL_SOCK 1`r`n#define PJMEDIA_HAS_OPUS_CODEC 1"
      shell: powershell
    - name: check VsDevCmd.bat
      run: dir "%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
      shell: cmd
    - name: MSBuild Debug
      working-directory: ./pjproject
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        call "%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        set INCLUDE=%INCLUDE%;%OPENSSL_DIR%\include;%cd%\..\win_x86-64\opus-1.3.1\include;%cd%\..\win_x86-64\opus-1.3.1\include\opus
        set LIB=%LIB%;%OPENSSL_DIR%\lib;%cd%\..\win_x86-64\opus-1.3.1\win32\VS2015\Win32\Debug
        msbuild pjproject-vs14.sln /p:PlatformToolset=v142 /p:Configuration=Debug-Dynamic /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - name: MSBuild Release
      working-directory: ./pjproject
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        call "%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        set INCLUDE=%INCLUDE%;%OPENSSL_DIR%\include;%cd%\..\win_x86-64\opus-1.3.1\include;%cd%\..\win_x86-64\opus-1.3.1\include\opus
        set LIB=%LIB%;%OPENSSL_DIR%\lib;%cd%\..\win_x86-64\opus-1.3.1\win32\VS2015\Win32\Release
        msbuild pjproject-vs14.sln /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd
    - name: delete previous lib
      continue-on-error: true
      run: |
        rm -r win_x86-64\lib
        rm -r win_x86-64\include
        Get-ChildItem -Include *.pdb -File -Recurse -ErrorAction SilentlyContinue
      shell: powershell
    - name: copy Assets
      run: |
        md win_x86-64\lib -Force | Out-Null
        md win_x86-64\include -Force | Out-Null
        Copy-Item -Path pjproject\pjsip\include\*,pjproject\pjlib\include\*,pjproject\pjlib-util\include\*,pjproject\pjmedia\include\*,pjproject\pjnath\include\* -Destination win_x86-64\include -Recurse
        Copy-Item -Path pjproject\lib\*.lib,pjproject\pjlib\lib\*.lib,pjproject\pjlib-util\lib\*.lib,pjproject\pjnath\lib\*.lib,pjproject\pjmedia\lib\*.lib,pjproject\pjsip\lib\*.lib,pjproject\third_party\lib\*.lib -Destination win_x86-64\lib -Recurse
        Copy-Item -Path pjproject\lib\*.bsc,pjproject\pjlib\lib\*.bsc,pjproject\pjlib-util\lib\*.bsc,pjproject\pjnath\lib\*.bsc,pjproject\pjmedia\lib\*.bsc,pjproject\pjsip\lib\*.bsc,pjproject\third_party\lib\*.bsc -Destination win_x86-64\lib -Recurse
      shell: powershell
    - name: Commit Libs
      continue-on-error: true
      run: |
        git config --global user.name 'AWAH-SIP_CI'
        git config --global user.email 'AWAH-SIP@users.noreply.github.com'
        git pull
        git add win_x86-64/\*
        git commit -m "Github Actions updated PJSIP-Libraries for win_x86-64"
        git push

  build-pjsip-RPi4:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./linux_arm_rpi4/Raspberry-Build-Docker
        push: false
        tags: rpi-pjsip-builder:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/rpi-pjsip-builder.tar
    - name: delete previous lib
      continue-on-error: true
      run: |
        rm -r linux_arm_rpi4/lib
        rm -r linux_arm_rpi4/include
    - name: Run Build in Container
      run: |
        docker load --input /tmp/rpi-pjsip-builder.tar
        echo $PWD
        docker run --rm -v $PWD/pjproject:/var/src -v $PWD/linux_arm_rpi4:/var/build rpi-pjsip-builder build
    - name: Commit Libs
      continue-on-error: true
      run: |
        git config --global user.name 'AWAH-SIP_CI'
        git config --global user.email 'AWAH-SIP@users.noreply.github.com'
        git pull
        git add linux_arm_rpi4/\*
        git commit -m "Github Actions updated PJSIP-Libraries for linux_arm_rpi4"
        git push
        
