name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-pjsip-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y libopencore-amrnb-dev libopus-dev
    - name: configure
      working-directory: ./pjproject
      run: ./configure --prefix=$PWD/../linux_x86-64
    - name: make
      working-directory: ./pjproject
      run: make
    - name: unit tests
      working-directory: ./pjproject
      run: make pjsip-test
    - name: make install
      working-directory: ./pjproject
      run: make install

