name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-pjsip-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: sudo apt-get install -y libopencore-amrnb-dev libopus-dev libasound2-dev
    - name: configure
      working-directory: ./pjproject
      run: ./configure --prefix=$PWD/../linux_x86-64
    - name: make
      working-directory: ./pjproject
      run: make
#    - name: unit tests
#      working-directory: ./pjproject
#      run: make pjsip-test
    - name: delete previous lib
      continue-on-error: true
      run: |
        rm -r linux_x86-64/lib
        rm -r linux_x86-64/include
    - name: make install
      working-directory: ./pjproject
      run: make install
    - name: Commit report
      run: |
        git config --global user.name 'AWAH-SIP_CI'
        git config --global user.email 'AWAH-SIP@users.noreply.github.com'
        git add linux_x86-64/\*
        git commit -m "Github Actions updated PJSIP-Libraries for linux_x86-64"
        git push
#    - name: Upload a Build Artifact
#      uses: actions/upload-artifact@v2.2.4
#      with:
#        name: linux_x86-64_Assets
#        path: linux_x86-64/*

