name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-pjsip-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: sudo apt-get install -y libopencore-amrnb-dev libopus-dev libasound2-dev
    - name: configure
      working-directory: ./pjproject
      run: ./configure --prefix=$PWD/../linux_x86-64
    - name: make
      working-directory: ./pjproject
      run: make
    - name: delete previous lib
      continue-on-error: true
      run: |
        rm -r linux_x86-64/lib
        rm -r linux_x86-64/include
    - name: make install
      working-directory: ./pjproject
      run: make install
    - name: Commit report
      run: |
        git config --global user.name 'AWAH-SIP_CI'
        git config --global user.email 'AWAH-SIP@users.noreply.github.com'
        git rm --cached linux_x86-64/include/\*
        git rm --cached linux_x86-64/lib/\*
        git add linux_x86-64/\*
        git commit -m "Github Actions updated PJSIP-Libraries for linux_x86-64"
        git push

  build-pjsip-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install dependencies
      run: brew install opencore-amr
    - name: configure
      working-directory: ./pjproject
      run: CFLAGS="-I/usr/local/include -I/usr/local/opt/openssl/include" LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib" ./configure --prefix=$PWD/../mac_x86-64
    - name: make
      working-directory: ./pjproject
      run: make
    - name: delete previous lib
      continue-on-error: true
      run: |
        rm -r mac_x86-64/lib
        rm -r mac_x86-64/include
    - name: make install
      working-directory: ./pjproject
      run: make install
    - name: Commit report
      run: |
        git config --global user.name 'AWAH-SIP_CI'
        git config --global user.email 'AWAH-SIP@users.noreply.github.com'
        git rm --cached mac_x86-64/include/\*
        git rm --cached mac_x86-64/lib/\*
        git add mac_x86-64/\*
        git commit -m "Github Actions updated PJSIP-Libraries for mac_x86-64"
        git push

  build-pjsip-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: get openssl
      run: Invoke-WebRequest -Uri "https://mirror.firedaemon.com/OpenSSL/openssl-1.1.1l-dev.zip" -OutFile ".\openssl.zip"
      shell: powershell
    - name: expand openssl
      run: |
        Expand-Archive -LiteralPath .\openssl.zip -DestinationPath .\openssl_build\; pwd
        cd openssl_build\openssl-1.1\x86
        Add-Content ..\..\..\openssl_dir.txt $pwd.Path
      shell: powershell
    - name: check openssl folder
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        dir "%OPENSSL_DIR%\include"
        dir "%OPENSSL_DIR%\lib"
      shell: cmd
    - name: config site
      run:
        cd pjproject/pjlib/include/pj; Add-Content config_site.h "#define PJ_HAS_SSL_SOCK 1"
      shell: powershell
    - name: check VsDevCmd.bat
      run: dir "%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
      shell: cmd
    - name: MSBuild
      working-directory: ./pjproject
      run: |
        set /P OPENSSL_DIR=<openssl_dir.txt
        call "%PROGRAMFILES(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        set INCLUDE=%INCLUDE%;%OPENSSL_DIR%\include;%cd%\..\win_x86-64\opus-1.3.1\include
        set LIB=%LIB%;%OPENSSL_DIR%\lib;%cd%\..\win_x86-64\opus-1.3.1\win32\VS2015\x64\Release
        set PJMEDIA_HAS_OPUS_CODEC=1
        msbuild pjproject-vs14.sln /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=win32 /p:UseEnv=true
      shell: cmd
